### ISSUE TITLE
tail_length_mode defined as integer[]

### ISSUE THREAD

**Issue by ilyaivjev** [wgnet/wg_forge_backend#1]
Почему tail_length_mode в таблице cats_stat определен как массив чисел? Нужно считать моду для котов каждой расцветки отдельно и затем сохранять как массив или в задании имелось в виду нечто другое?

**Comment by yzh44yzh** [comment]
Мода -- это значение, которое встречается чаще всего в выборке. Но таких значений может быть больше одного. 

Например, если у нас выборка из 5 котов с хвостами: 10,12,12,14,17. То здесь мода будет 12.
А если выборка: 10,10,12,12,14, то мода будет [10, 12].
