### ISSUE TITLE
Требуется ли описание полноценного деплоя выполненного тестового задания?

### ISSUE THREAD

**Issue by MIKSby** [wgnet/wg_forge_backend#2]
Нужно ли описывать установку/настройку uWSGI/gunicorn, конфигурирование nginx и т.д. для деплоя тестового задания, либо достаточным будет использование стандартного development-сервера на локальном хосте ( например http://flask.pocoo.org/docs/1.0/server/) плюс перечень необходимых для функционирования приложения пакетов в requirements.txt  ?

**Comment by yzh44yzh** [comment]
достаточно запуска на локальном хосте и списка зависимостей
